#実行環境のDockerコンテナ

FROM ubuntu:16.04

#apt の更新をかける
RUN apt update -y
RUN apt upgrade -y

#Gitをインストール（儀っとを入れなくてもwgetでひっぱれるのでは？
RUN apt install git -y

#curl install
RUN apt install curl -y

#Nodejs 8.9.2
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

#BookChainを動かす
RUN apt install make -y
RUN apt install g++ -y

CMD ["npm", "start"]
EXPOSE 80
EXPOSE 8080
