#実行環境のDockerコンテナ

FROM ubuntu:16.04

#apt の更新をかける
RUN apt update -y
RUN apt upgrade -y

#Gitをインストール（儀っとを入れなくてもwgetでひっぱれるのでは？
RUN apt install git -y

#curl install
RUN apt install curl -y

#Nodejs 8.9.2
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

#gitのクローンはこのフォルダで行う
WORKDIR /opt

#BookChain-Clientをpull
RUN git clone https://github.com/kbc-itw/BookChain-Client.git
WORKDIR ./BookChain-Client
RUN npm install
RUN npm run build

#BookChainのパブリックフォルダにビルドしたものを入れる
RUN mkdir /opt/public
RUN mv dist/* /opt/public

#BookChain
WORKDIR /opt
RUN git clone https://github.com/kbc-itw/BookChain.git
WORKDIR ./BookChain
RUN npm install
RUN npm run build
CMD ["npm", "start"]
EXPOSE 80
