#実行環境のDockerコンテナ

FROM ubuntu:16.04

#apt の更新をかける
RUN apt update -y
RUN apt upgrade -y

#Gitをインストール（儀っとを入れなくてもwgetでひっぱれるのでは？
RUN apt install git -y



#Nodejs 8.8.1

RUN apt install nodejs -y
RUN apt install npm -y
RUN npm cache clean
RUN npm install n -g
RUN n stable
RUN n 8.8.1
RUN node -v

WORKDIR /opt

#BookChain
RUN git clone https://github.com/kbc-itw/BookChain.git
WORKDIR ./BookChain
RUN npm install
RUN npm start

RUN apt update -y
RUN apt upgrade -y

